# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import clients_pb2 as clients__pb2
import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in clients_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/emergency.ClientService/Register',
                request_serializer=clients__pb2.RegisterRequest.SerializeToString,
                response_deserializer=clients__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.RequestEmergency = channel.unary_unary(
                '/emergency.ClientService/RequestEmergency',
                request_serializer=clients__pb2.EmergencyRequest.SerializeToString,
                response_deserializer=clients__pb2.EmergencyResponse.FromString,
                _registered_method=True)
        self.WatchSessionStatus = channel.unary_stream(
                '/emergency.ClientService/WatchSessionStatus',
                request_serializer=clients__pb2.WatchSessionRequest.SerializeToString,
                response_deserializer=clients__pb2.SessionUpdate.FromString,
                _registered_method=True)
        self.ChatStream = channel.stream_stream(
                '/emergency.ClientService/ChatStream',
                request_serializer=common__pb2.ChatMessage.SerializeToString,
                response_deserializer=common__pb2.ChatMessage.FromString,
                _registered_method=True)


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestEmergency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchSessionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=clients__pb2.RegisterRequest.FromString,
                    response_serializer=clients__pb2.RegisterResponse.SerializeToString,
            ),
            'RequestEmergency': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestEmergency,
                    request_deserializer=clients__pb2.EmergencyRequest.FromString,
                    response_serializer=clients__pb2.EmergencyResponse.SerializeToString,
            ),
            'WatchSessionStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchSessionStatus,
                    request_deserializer=clients__pb2.WatchSessionRequest.FromString,
                    response_serializer=clients__pb2.SessionUpdate.SerializeToString,
            ),
            'ChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=common__pb2.ChatMessage.FromString,
                    response_serializer=common__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emergency.ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('emergency.ClientService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.ClientService/Register',
            clients__pb2.RegisterRequest.SerializeToString,
            clients__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestEmergency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.ClientService/RequestEmergency',
            clients__pb2.EmergencyRequest.SerializeToString,
            clients__pb2.EmergencyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/emergency.ClientService/WatchSessionStatus',
            clients__pb2.WatchSessionRequest.SerializeToString,
            clients__pb2.SessionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/emergency.ClientService/ChatStream',
            common__pb2.ChatMessage.SerializeToString,
            common__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
