# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clients.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'clients.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rclients.proto\x12\temergency\x1a\x0c\x63ommon.proto\"$\n\x0fRegisterRequest\x12\x11\n\tphone_num\x18\x01 \x01(\t\"W\n\x10RegisterResponse\x12!\n\x06\x63lient\x18\x01 \x01(\x0b\x32\x11.emergency.Client\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\">\n\x10\x45mergencyRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x17\n\x0finitial_message\x18\x02 \x01(\t\"\x8c\x01\n\x11\x45mergencyResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12+\n\trouted_to\x18\x02 \x01(\x0e\x32\x18.emergency.EmergencyType\x12(\n\x06status\x18\x03 \x01(\x0e\x32\x18.emergency.RequestStatus\x12\x0c\n\x04info\x18\x04 \x01(\t\"<\n\x13WatchSessionRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\"J\n\rSessionUpdate\x12#\n\x07session\x18\x01 \x01(\x0b\x32\x12.emergency.Session\x12\x14\n\x0cnotification\x18\x02 \x01(\t2\xb7\x02\n\rClientService\x12\x43\n\x08Register\x12\x1a.emergency.RegisterRequest\x1a\x1b.emergency.RegisterResponse\x12M\n\x10RequestEmergency\x12\x1b.emergency.EmergencyRequest\x1a\x1c.emergency.EmergencyResponse\x12P\n\x12WatchSessionStatus\x12\x1e.emergency.WatchSessionRequest\x1a\x18.emergency.SessionUpdate0\x01\x12@\n\nChatStream\x12\x16.emergency.ChatMessage\x1a\x16.emergency.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clients_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=42
  _globals['_REGISTERREQUEST']._serialized_end=78
  _globals['_REGISTERRESPONSE']._serialized_start=80
  _globals['_REGISTERRESPONSE']._serialized_end=167
  _globals['_EMERGENCYREQUEST']._serialized_start=169
  _globals['_EMERGENCYREQUEST']._serialized_end=231
  _globals['_EMERGENCYRESPONSE']._serialized_start=234
  _globals['_EMERGENCYRESPONSE']._serialized_end=374
  _globals['_WATCHSESSIONREQUEST']._serialized_start=376
  _globals['_WATCHSESSIONREQUEST']._serialized_end=436
  _globals['_SESSIONUPDATE']._serialized_start=438
  _globals['_SESSIONUPDATE']._serialized_end=512
  _globals['_CLIENTSERVICE']._serialized_start=515
  _globals['_CLIENTSERVICE']._serialized_end=826
# @@protoc_insertion_point(module_scope)
