# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\temergency\"A\n\x06\x43lient\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x11\n\tphone_num\x18\x02 \x01(\t\x12\x11\n\tis_banned\x18\x03 \x01(\x08\"[\n\x0bHelperAgent\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\ndepartment\x18\x03 \x01(\x0e\x32\x18.emergency.EmergencyType\"\xef\x01\n\x07Session\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12!\n\x06\x63lient\x18\x02 \x01(\x0b\x32\x11.emergency.Client\x12.\n\x0e\x61ssigned_agent\x18\x03 \x01(\x0b\x32\x16.emergency.HelperAgent\x12&\n\x04type\x18\x04 \x01(\x0e\x32\x18.emergency.EmergencyType\x12(\n\x06status\x18\x05 \x01(\x0e\x32\x18.emergency.RequestStatus\x12\x17\n\x0finitial_message\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\x03\"\x84\x01\n\x0b\x43hatMessage\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12*\n\x0bsender_role\x18\x03 \x01(\x0e\x32\x15.emergency.SenderRole\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03*?\n\rEmergencyType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04\x46IRE\x10\x01\x12\x0b\n\x07MEDICAL\x10\x02\x12\n\n\x06POLICE\x10\x03*?\n\rRequestStatus\x12\x0b\n\x07PENDING\x10\x00\x12\x0b\n\x07ONGOING\x10\x01\x12\x08\n\x04\x44ONE\x10\x02\x12\n\n\x06\x42\x41NNED\x10\x03*$\n\nSenderRole\x12\n\n\x06\x43LIENT\x10\x00\x12\n\n\x06HELPER\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMERGENCYTYPE']._serialized_start=564
  _globals['_EMERGENCYTYPE']._serialized_end=627
  _globals['_REQUESTSTATUS']._serialized_start=629
  _globals['_REQUESTSTATUS']._serialized_end=692
  _globals['_SENDERROLE']._serialized_start=694
  _globals['_SENDERROLE']._serialized_end=730
  _globals['_CLIENT']._serialized_start=27
  _globals['_CLIENT']._serialized_end=92
  _globals['_HELPERAGENT']._serialized_start=94
  _globals['_HELPERAGENT']._serialized_end=185
  _globals['_SESSION']._serialized_start=188
  _globals['_SESSION']._serialized_end=427
  _globals['_CHATMESSAGE']._serialized_start=430
  _globals['_CHATMESSAGE']._serialized_end=562
# @@protoc_insertion_point(module_scope)
