# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dispatcher.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dispatcher.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64ispatcher.proto\x12\temergency\x1a\x0c\x63ommon.proto\";\n\x0cRouteRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x17\n\x0finitial_message\x18\x02 \x01(\t\"a\n\rRouteResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12+\n\trouted_to\x18\x02 \x01(\x0e\x32\x18.emergency.EmergencyType\x12\x0f\n\x07success\x18\x03 \x01(\x08\"i\n\x0fGetQueueRequest\x12,\n\ndepartment\x18\x01 \x01(\x0e\x32\x18.emergency.EmergencyType\x12(\n\x06\x66ilter\x18\x02 \x01(\x0e\x32\x18.emergency.RequestStatus\"d\n\x10GetQueueResponse\x12#\n\x07PENDING\x18\x01 \x03(\x0b\x32\x12.emergency.Session\x12\x15\n\rtotal_pending\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_active\x18\x03 \x01(\x05\"j\n\x14UpdateSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12,\n\nnew_status\x18\x02 \x01(\x0e\x32\x18.emergency.RequestStatus\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\"U\n\x15UpdateSessionResponse\x12+\n\x0fupdated_session\x18\x01 \x01(\x0b\x32\x12.emergency.Session\x12\x0f\n\x07success\x18\x02 \x01(\x08\"[\n\x10\x42\x61nClientRequest\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\"G\n\x11\x42\x61nClientResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12!\n\x06\x63lient\x18\x02 \x01(\x0b\x32\x11.emergency.Client2\x83\x03\n\x0f\x44ispatchService\x12\x43\n\x0eRouteEmergency\x12\x17.emergency.RouteRequest\x1a\x18.emergency.RouteResponse\x12\x43\n\x08GetQueue\x12\x1a.emergency.GetQueueRequest\x1a\x1b.emergency.GetQueueResponse\x12X\n\x13UpdateSessionStatus\x12\x1f.emergency.UpdateSessionRequest\x1a .emergency.UpdateSessionResponse\x12\x46\n\tBanClient\x12\x1b.emergency.BanClientRequest\x1a\x1c.emergency.BanClientResponse\x12\x44\n\x10WatchAllSessions\x12\x1a.emergency.GetQueueRequest\x1a\x12.emergency.Session0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispatcher_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROUTEREQUEST']._serialized_start=45
  _globals['_ROUTEREQUEST']._serialized_end=104
  _globals['_ROUTERESPONSE']._serialized_start=106
  _globals['_ROUTERESPONSE']._serialized_end=203
  _globals['_GETQUEUEREQUEST']._serialized_start=205
  _globals['_GETQUEUEREQUEST']._serialized_end=310
  _globals['_GETQUEUERESPONSE']._serialized_start=312
  _globals['_GETQUEUERESPONSE']._serialized_end=412
  _globals['_UPDATESESSIONREQUEST']._serialized_start=414
  _globals['_UPDATESESSIONREQUEST']._serialized_end=520
  _globals['_UPDATESESSIONRESPONSE']._serialized_start=522
  _globals['_UPDATESESSIONRESPONSE']._serialized_end=607
  _globals['_BANCLIENTREQUEST']._serialized_start=609
  _globals['_BANCLIENTREQUEST']._serialized_end=700
  _globals['_BANCLIENTRESPONSE']._serialized_start=702
  _globals['_BANCLIENTRESPONSE']._serialized_end=773
  _globals['_DISPATCHSERVICE']._serialized_start=776
  _globals['_DISPATCHSERVICE']._serialized_end=1163
# @@protoc_insertion_point(module_scope)
