# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import dispatcher_pb2 as dispatcher__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dispatcher_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DispatchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RouteEmergency = channel.unary_unary(
                '/emergency.DispatchService/RouteEmergency',
                request_serializer=dispatcher__pb2.RouteRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.RouteResponse.FromString,
                _registered_method=True)
        self.GetQueue = channel.unary_unary(
                '/emergency.DispatchService/GetQueue',
                request_serializer=dispatcher__pb2.GetQueueRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.GetQueueResponse.FromString,
                _registered_method=True)
        self.UpdateSessionStatus = channel.unary_unary(
                '/emergency.DispatchService/UpdateSessionStatus',
                request_serializer=dispatcher__pb2.UpdateSessionRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.UpdateSessionResponse.FromString,
                _registered_method=True)
        self.BanClient = channel.unary_unary(
                '/emergency.DispatchService/BanClient',
                request_serializer=dispatcher__pb2.BanClientRequest.SerializeToString,
                response_deserializer=dispatcher__pb2.BanClientResponse.FromString,
                _registered_method=True)
        self.WatchAllSessions = channel.unary_stream(
                '/emergency.DispatchService/WatchAllSessions',
                request_serializer=dispatcher__pb2.GetQueueRequest.SerializeToString,
                response_deserializer=common__pb2.Session.FromString,
                _registered_method=True)


class DispatchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RouteEmergency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSessionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BanClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchAllSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DispatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RouteEmergency': grpc.unary_unary_rpc_method_handler(
                    servicer.RouteEmergency,
                    request_deserializer=dispatcher__pb2.RouteRequest.FromString,
                    response_serializer=dispatcher__pb2.RouteResponse.SerializeToString,
            ),
            'GetQueue': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueue,
                    request_deserializer=dispatcher__pb2.GetQueueRequest.FromString,
                    response_serializer=dispatcher__pb2.GetQueueResponse.SerializeToString,
            ),
            'UpdateSessionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSessionStatus,
                    request_deserializer=dispatcher__pb2.UpdateSessionRequest.FromString,
                    response_serializer=dispatcher__pb2.UpdateSessionResponse.SerializeToString,
            ),
            'BanClient': grpc.unary_unary_rpc_method_handler(
                    servicer.BanClient,
                    request_deserializer=dispatcher__pb2.BanClientRequest.FromString,
                    response_serializer=dispatcher__pb2.BanClientResponse.SerializeToString,
            ),
            'WatchAllSessions': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchAllSessions,
                    request_deserializer=dispatcher__pb2.GetQueueRequest.FromString,
                    response_serializer=common__pb2.Session.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emergency.DispatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('emergency.DispatchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DispatchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RouteEmergency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.DispatchService/RouteEmergency',
            dispatcher__pb2.RouteRequest.SerializeToString,
            dispatcher__pb2.RouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.DispatchService/GetQueue',
            dispatcher__pb2.GetQueueRequest.SerializeToString,
            dispatcher__pb2.GetQueueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSessionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.DispatchService/UpdateSessionStatus',
            dispatcher__pb2.UpdateSessionRequest.SerializeToString,
            dispatcher__pb2.UpdateSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BanClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.DispatchService/BanClient',
            dispatcher__pb2.BanClientRequest.SerializeToString,
            dispatcher__pb2.BanClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchAllSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/emergency.DispatchService/WatchAllSessions',
            dispatcher__pb2.GetQueueRequest.SerializeToString,
            common__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
