# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import common_pb2 as common__pb2
import helper_pb2 as helper__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in helper_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HelperServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/emergency.HelperService/Login',
                request_serializer=helper__pb2.HelperLoginRequest.SerializeToString,
                response_deserializer=helper__pb2.HelperLoginResponse.FromString,
                _registered_method=True)
        self.WatchQueue = channel.unary_stream(
                '/emergency.HelperService/WatchQueue',
                request_serializer=helper__pb2.WatchQueueRequest.SerializeToString,
                response_deserializer=helper__pb2.QueueUpdate.FromString,
                _registered_method=True)
        self.AssignClient = channel.unary_unary(
                '/emergency.HelperService/AssignClient',
                request_serializer=helper__pb2.AssignRequest.SerializeToString,
                response_deserializer=helper__pb2.AssignResponse.FromString,
                _registered_method=True)
        self.ChatStream = channel.stream_stream(
                '/emergency.HelperService/ChatStream',
                request_serializer=common__pb2.ChatMessage.SerializeToString,
                response_deserializer=common__pb2.ChatMessage.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/emergency.HelperService/EndSession',
                request_serializer=helper__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=helper__pb2.EndSessionResponse.FromString,
                _registered_method=True)


class HelperServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchQueue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChatStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HelperServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=helper__pb2.HelperLoginRequest.FromString,
                    response_serializer=helper__pb2.HelperLoginResponse.SerializeToString,
            ),
            'WatchQueue': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchQueue,
                    request_deserializer=helper__pb2.WatchQueueRequest.FromString,
                    response_serializer=helper__pb2.QueueUpdate.SerializeToString,
            ),
            'AssignClient': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignClient,
                    request_deserializer=helper__pb2.AssignRequest.FromString,
                    response_serializer=helper__pb2.AssignResponse.SerializeToString,
            ),
            'ChatStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=common__pb2.ChatMessage.FromString,
                    response_serializer=common__pb2.ChatMessage.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=helper__pb2.EndSessionRequest.FromString,
                    response_serializer=helper__pb2.EndSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'emergency.HelperService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('emergency.HelperService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HelperService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.HelperService/Login',
            helper__pb2.HelperLoginRequest.SerializeToString,
            helper__pb2.HelperLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchQueue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/emergency.HelperService/WatchQueue',
            helper__pb2.WatchQueueRequest.SerializeToString,
            helper__pb2.QueueUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.HelperService/AssignClient',
            helper__pb2.AssignRequest.SerializeToString,
            helper__pb2.AssignResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ChatStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/emergency.HelperService/ChatStream',
            common__pb2.ChatMessage.SerializeToString,
            common__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/emergency.HelperService/EndSession',
            helper__pb2.EndSessionRequest.SerializeToString,
            helper__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
